language: python
sudo: false

matrix:
  include:
    # Lint
    - python: 2.7
      env: TOXENV=lint
    - python: 3.6
      env: TOXENV=lint

    # Packaging
    - python: 3.6
      env: TOXENV=packaging

    # Building Library.py
    - python: 2.7
      env: TOXENV=build

    - python: 3.6
      env: TOXENV=build

cache:
  - pip
  - directories:
    - ${HOME}/.cache

install:
  - python -m pip install -U tox setuptools pip

script:
  - tox

notifications:
  email: false

branches:
  only:
  - master
